#dbUserPasswords:
#  dbuserPassword: ""

databases:
  mosip_mockidentitysystem:
    enabled: true
    scriptsDir: mosip_mockidentitysystem  # fixed - must match db_scripts/ folder in repo
    dbName: mosip_mockidentitysystem      # customize e.g. mosip_mockidentitysystem02
    dbUser: mockidentityuser              # customize e.g. mockidentityuser02
    defaultDb: postgres
    host: "postgres-postgresql.postgres"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/esignet-mock-services.git
    branch: release-0.14.x
