image:
  registry: docker.io
  repository: mosipdev/partner-onboarder
  tag: MOSIP-35987

onboarding:
  modules:
    - name: ida
      enabled: false
    - name: print
      enabled: false
    - name: abis
      enabled: false
    - name: resident
      enabled: false
    - name: mobileid
      enabled: false
    - name: digitalcard
      enabled: false
    - name: esignet
      enabled: false
    - name: resident-oidc
      enabled: false
    - name: mock-rp-oidc
      enabled: true
    - name: mimoto-keybinding
      enabled: false
    - name: mimoto-oidc
      enabled: false
    - name: signup-oidc
      enabled: false

#  volumes:
#    reports:
#      enabled: true
#      name: onboarder-reports
#      storageClass: nfs-client
#      accessModes:
#        - ReadWriteMany
#      size: 10Mi
#      existingClaim:
#      # Dir where config and keys are written inside container
#      mountDir: "/home/mosip/reports"
#      nfs:
#        path: ''  # Dir within the nfs server where config repo is cloned/maintained locally.
#        server: ''  # Ip address of nfs server.
#  variables:
#    push-reports-to-s3: true
